# Logging levels for various mechanics.
# Levels are generally 1, 2, or 3 where:
#   0 to disable logging,
#   1 is sparse logging,
#   2 is verbose logging,
#   3 is excessive logging.
logging:
  # Messages during initialization.
  setup: 0
  # Messages for zone management under protection.
  zone: 0
  # Messages for hologram management.
  hologram: 0
  # Messages from the server.
  server: 0
  # Messages from vanilla minecraft.
  minecraft: 0
